### PR TITLE
Remove RC_SHARED_OR_STATIC option and document use of canonical BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by Thorius**

### CODE REVIEW

**Comment by Thorius** [comment]
@janisozaur, can you check if this is ok? I simply reverted my old commit and added a comment on how to handle certain use-cases.

**Comment by janisozaur** [comment]
Other than a bit too long commit message subjects (they should not wrap in GitHub's webui, 72 chars, and ideally follow https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) I would suggest changing the description from "internal" to "global", as per docs. Naming it internal may make people think it's not meant for public usage.

**Comment by emil-e** [comment]
I agree with @janisozaur, otherwise seems good to me.

I don't have that many personal opinions on these things given that I only use RapidCheck myself as a submodule.

**Comment by Thorius** [comment]
For the commit messages, I am used to other other code review platforms (i.e. Crucible) and I typically write a bit longer messages but you are absolutely right that it is a bit unpleasant here. I will set some guidelines in my editor to prevent this in the future.

I meant internal as in built into CMake but you are right that it might cause confusion. I will change it to global and push

**Pull request merged**
